name: padel_app
description: Padel booking, matchmaking and tournaments app
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  flutter_animate: ^4.5.0

  # State Management
  provider: ^6.1.1

  # HTTP & API
  dio: ^5.4.0

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.4

  # Real-time
  socket_io_client: ^2.0.3+1

  # Navigation & Deep linking
  go_router: ^13.0.0
  app_links: ^6.3.2

  # Utils
  intl: any
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
